# Generated by Django 5.2 on 2025-04-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('prica', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.BooleanField()),
            ],
            options={
                'db_table': 'books',
                'indexes': [models.Index(fields=['available'], name='books_availab_c33253_idx')],
            },
        ),
    ]
